(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.CNABBankModules.bradesco.constants=api})(typeof globalThis!=="undefined"?globalThis:this,function(){"use strict";
  const OCCURRENCES=Object.freeze({
    "00":"Crédito ou Débito Efetivado","01":"Insuficiência de Fundos — Débito Não Efetuado","02":"Crédito ou Débito Cancelado pelo Pagador/Credor","03":"Débito Autorizado pela Agência — Efetuado",
    AA:"Controle Inválido",AB:"Tipo de Operação Inválido",AC:"Tipo de Serviço Inválido",AD:"Forma de Lançamento Inválida",AE:"Tipo/Número de Inscrição Inválido",AF:"Código de Convênio Inválido",
    AG:"Agência/Conta Corrente/DV Inválido",AH:"Nº Sequencial do Registro no Lote Inválido",AI:"Código de Segmento de Detalhe Inválido",AJ:"Tipo de Movimento Inválido",
    AK:"Código da Câmara de Compensação do Banco Favorecido/Depositário Inválido",AL:"Banco Favorecido Inoperante ou Depositário Inválido",AM:"Agência do Favorecido Inválida",AN:"Conta/DV do Favorecido Inválido",AO:"Nome do Favorecido Não Informado",AP:"Data de Lançamento Inválida",AQ:"Tipo/Quantidade da Moeda Inválido",AR:"Valor do Lançamento Inválido",AS:"Aviso ao Favorecido — Identificação Inválida",AT:"Tipo/Número de Inscrição do Favorecido Inválido",AU:"Logradouro do Favorecido Não Informado",AV:"Nº do Local do Favorecido Não Informado",AW:"Cidade do Favorecido Não Informada",AX:"CEP/Complemento do Favorecido Inválido",AY:"UF do Favorecido Inválida",AZ:"Código/Nome do Banco Depositário Inválido",
    BA:"Código/Nome da Agência Depositária Não Informado",BB:"Seu Número Inválido",BC:"Nosso Número Inválido",BD:"Inclusão Efetuada com Sucesso",BE:"Alteração Efetuada com Sucesso",BF:"Exclusão Efetuada com Sucesso",BG:"Agência/Conta Impedida Legalmente",BH:"Empresa não pagou salário",BI:"Falecimento do mutuário",BJ:"Empresa não enviou remessa do mutuário",BK:"Empresa não enviou remessa no vencimento",BL:"Valor da parcela inválida",BM:"Identificação do contrato inválida",BN:"Consignação Incluída com Sucesso",BO:"Consignação Alterada com Sucesso",BP:"Consignação Excluída com Sucesso",BQ:"Consignação Liquidada com Sucesso",
    CA:"Código de Barras — Código do Banco Inválido",CB:"Código de Barras — Código da Moeda Inválido",CC:"Código de Barras — Dígito Verificador Geral Inválido",CD:"Código de Barras — Valor do Título Divergente/Inválido",CE:"Código de Barras — Campo Livre Inválido",CF:"Valor do Documento Inválido",CG:"Valor do Abatimento Inválido",CH:"Valor do Desconto Inválido",CI:"Valor de Mora Inválido",CJ:"Valor da Multa Inválido",CK:"Valor do IR Inválido",CL:"Valor do ISS Inválido",CM:"Valor do IOF Inválido",CN:"Valor de Outras Deduções Inválido",CO:"Valor de Outros Acréscimos Inválido",CP:"Valor do INSS Inválido",
    HA:"Lote Não Aceito",HB:"Inscrição da Empresa Inválida para o Contrato",HC:"Convênio Inexistente/Inválido para o Contrato",HD:"Agência/Conta da Empresa Inexistente/Inválida",HE:"Tipo de Serviço Inválido para o Contrato",HF:"Conta da Empresa com Saldo Insuficiente",HG:"Lote de Serviço Fora de Sequência",HH:"Lote de Serviço Inválido",HI:"Arquivo Não Aceito",HJ:"Tipo de Registro Inválido",HK:"Código Remessa/Retorno Inválido",HL:"Versão de Layout Inválida",HM:"Mutuário Não Identificado",HN:"Tipo do Benefício Não Permite Empréstimo",HO:"Benefício Cessado/Suspenso",HP:"Benefício Possui Representante Legal",HQ:"Benefício é do Tipo PA",HR:"Quantidade de Contratos Excedida",HS:"Benefício Não Pertence ao Banco Informado",HT:"Início do Desconto Já Ultrapassado",HU:"Número da Parcela Inválido",HV:"Quantidade de Parcela Inválida",HW:"Margem Consignável Excedida",HX:"Empréstimo Já Cadastrado",HY:"Empréstimo Inexistente",HZ:"Empréstimo Já Encerrado",H1:"Arquivo sem Trailer",H2:"Mutuário sem Crédito na Competência",H3:"Não Descontado — Outros Motivos",H4:"Retorno de Crédito Não Pago",H5:"Cancelamento de Empréstimo Retroativo",H6:"Outros Motivos de Glosa",H7:"Margem Consignável Excedida Acima do Prazo",H8:"Mutuário Desligado do Empregador",H9:"Mutuário Afastado por Licença",
    IA:"Nome do Mutuário Divergente",TA:"Lote Não Aceito — Totais do Lote com Diferença",YA:"Título Não Encontrado",YB:"Identificador de Registro Opcional Inválido",YC:"Código Padrão Inválido",YD:"Código de Ocorrência Inválido",YE:"Complemento de Ocorrência Inválido",YF:"Alegação Já Informada",ZA:"Agência/Conta do Favorecido Substituída",ZB:"Beneficiário Divergente da Receita Federal",ZC:"Confirmação de Antecipação de Valor",ZD:"Antecipação Parcial de Valor",ZE:"Título Bloqueado na Base",ZF:"Contingência — Valor Maior que Referência",ZG:"Contingência — Título Vencido",ZH:"Contingência — Título Indexado",ZI:"Beneficiário Divergente dos Dados da CIP",ZJ:"Limite de Pagamentos Parciais Excedido",ZK:"Boleto Já Liquidado","5A":"Agendado sob Lista de Débito","5B":"Pagamento Não Autorizado sob Lista de Débito","5C":"Lista com Mais de uma Modalidade","5D":"Lista com Mais de uma Data de Pagamento","5E":"Número de Lista Duplicado","5F":"Lista Vencida e Não Autorizada","5I":"Ordem de Pagamento Emitida","5J":"Ordem de Pagamento com Data Limite Vencida","5M":"Número da Lista de Débito Inválido","5T":"Pagamento Realizado em Contrato de Teste"
  });
  return Object.freeze({BANK_CODE:"237",FILE_LAYOUT:"089",LOT_LAYOUTS:Object.freeze({payments:"045",titles:"040",taxes:"012"}),REGISTRATION_TYPES:Object.freeze({"0":"Isento/Não informado","1":"CPF","2":"CNPJ","3":"PIS/PASEP","9":"Outro"}),TAXPAYER_TYPES:Object.freeze({"01":"CNPJ","02":"CPF","03":"NIT/PIS/PASEP","04":"CEI","06":"NB","07":"Nº do Título","08":"DEBCAD","09":"Referência"}),CHAMBERS:Object.freeze({"018":"TED (STR/CIP)","700":"DOC (COMPE)","888":"TED por ISPB"}),OCCURRENCES});
});
